# Cloud Run Configuration
# https://cloud.google.com/sdk/gcloud/reference/run/deploy#OPTIONAL-FLAGS
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chat-api
spec:
  template:
    spec:
      containers:
        - image: gcr.io/awesome-nucleus-303917/chat-like-microservice:db55df0359af3e91753868214da7dec9d2157f05
          ports:
            - containerPort: 3000
          env:
            - name: PLUGINS
              value: 'CHAT_API'
            - name: CORS_ORIGIN_WHITELIST
              value: 'http://localhost:8001' # @TODO
            - name: VET_SHELTER_API_URL
              value: 'http://localhost:8000' # @TODO
            - name: RECOMMENDER_BOT_TOKEN
              value: 'NWYyNWI4MjVjMjc0ZmRjZWI1ZWFhYmQ4M2JlMzJiNzEK'
            - name: RECOMMENDER_BOT_USER_UUID
              value: 'b6256195-1ac6-4146-8d75-d796447c06ad'
            - name: CHAT_STORAGE
              value: 'memory'
            - name: CHAT_BROKER_ENABLED
              value: 'false'
