# Cloud Run Configuration
# https://cloud.google.com/sdk/gcloud/reference/run/deploy#OPTIONAL-FLAGS
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chat-api
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-connector: projects/wolke-sieben-fs/locations/europe-west3/connectors/chat-broker-connector
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - image: gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$IMAGE_VERSION
          resources:
            limits:
              cpu: '1'
              memory: 1000Mi
          ports:
            - containerPort: 3000
          env:
            - name: PLUGINS
              value: 'CHAT_API'
            - name: CORS_ORIGIN_WHITELIST
              value: 'https://cc-wolkesieben.de'
            - name: VET_SHELTER_API_URL
              value: 'https://app.cc-wolkesieben.de'
            - name: RECOMMENDER_BOT_TOKEN
              value: 'NWYyNWI4MjVjMjc0ZmRjZWI1ZWFhYmQ4M2JlMzJiNzEK'
            - name: RECOMMENDER_BOT_USER_UUID
              value: 'b6256195-1ac6-4146-8d75-d796447c06ad'
            - name: CHAT_STORAGE
              value: 'firestore'
            - name: CHAT_BROKER_ENABLED
              value: 'true'
            - name: CHAT_REDIS_CLIENT_ID
              value: '71ac9f3b-673c-498d-ad4d-5b92d12cc2b0'
            - name: CHAT_REDIS_HOST
              value: '10.122.97.235'
            - name: CHAT_REDIS_PORT
              value: '6379'
            - name: CHAT_REDIS_AUTH
              value: 'a4abdb8d-8268-4353-b0d7-18781c1c266e'
  traffic:
    - percent: 100
      latestRevision: true
