version: '3.4'

x-api-env: &api-env
  GCP_PROJECT_ID: vet-shelter # must match value passed to emulators

services:
  chat:
    image: chat-microservice
    build:
      context: .
    environment:
      <<: *api-env
      FIRESTORE_EMULATOR_HOST: firestore:8970
      PLUGINS: CHAT_API
      CHAT_STORAGE: firestore
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    ports:
      - 3000:3000
    depends_on:
      - firestore
    command: yarn start:dev

  like:
    image: like-microservice
    build:
      context: .
    environment:
      <<: *api-env
      BIGTABLE_EMULATOR_HOST: bigtable:8086
      PLUGINS: LIKE_API
      LIKE_STORAGE: memory
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    ports:
      - 3001:3000
    depends_on:
      - bigtable
    command: yarn start:dev

  # https://github.com/googleapis/nodejs-firestore/issues/1296#issuecomment-697948320
  firestore:
    image: google/cloud-sdk:emulators
    ports:
      - 8970:8970
    entrypoint: /bin/bash -c "gcloud config set project vet-shelter && /google-cloud-sdk/platform/cloud-firestore-emulator/cloud_firestore_emulator start --host=0.0.0.0 --port=8970"

  # https://github.com/googleapis/nodejs-bigtable/issues/612#issuecomment-589133501
  bigtable:
    image: google/cloud-sdk:emulators
    ports:
      - 8086:8086
    entrypoint: /bin/bash -c "gcloud config set project vet-shelter && /google-cloud-sdk/platform/bigtable-emulator/cbtemulator --host=0.0.0.0 --port=8086"
