name: Chat API Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/marketplace/actions/cancel-workflow-action
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout source code
        uses: actions/checkout@v2

      # https://github.com/google-github-actions/setup-gcloud/
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and push container image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/chat-like-api:${{  github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/chat-like-api:${{  github.sha }}
