name: Chat API Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ github.token }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  SERVICE_NAME: chat-api
  IMAGE_NAME: chat-like-microservice
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/marketplace/actions/cancel-workflow-action
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ env.GITHUB_TOKEN }}

      - name: Checkout source code
        uses: actions/checkout@v2

      # https://github.com/google-github-actions/setup-gcloud/
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install Google Cloud SDK beta components
        run: gcloud components install beta

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and push container image to Google Cloud Registry
        run: |
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} .
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

      - name: Update deployment specification
        uses: danielr1996/envsubst-action@1.0.0
        env:
          GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}
        with:
          input: chat.service.yaml
          output: chat.service.tmp.yaml

      # # https://github.com/google-github-actions/deploy-cloudrun
      # # service spec (`metadata`) cannot be used due to: https://github.com/google-github-actions/deploy-cloudrun/issues/26
      # - name: Deploy to Google Cloud Run
      #   uses: google-github-actions/deploy-cloudrun@v0.2.0
      #   with:
      #     project_id: ${{ env.GCP_PROJECT_ID }}
      #     region: europe-west3
      #     # metadata: chat.service.yaml
      #     service: ${{ env.SERVICE_NAME }}
      #     image: gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:db55df0359af3e91753868214da7dec9d2157f05

      - name: Deploy to Google Cloud Run
        run: gcloud beta run services replace chat.service.tmp.yaml --platform managed --region europe-west3
