name: Node.js CI

on: [workflow_dispatch, push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/marketplace/actions/cancel-workflow-action
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout source code
        uses: actions/checkout@v2

      # # https://github.com/marketplace/actions/docker-layer-caching
      # - name: Restore Docker image cache (1/2)
      #   run: docker-compose -f docker-compose.ci.yml pull
      # - name: Restore Docker image cache (2/2)
      #   uses: satackey/action-docker-layer-caching@v0.0.11
      #   continue-on-error: true

      - name: Build and start the Docker stack
        run: docker-compose -f docker-compose.ci.yml up -d --build

      - name: Test (Unit)
        run: docker-compose -f docker-compose.ci.yml exec -T api yarn test:cov
      - name: Test (E2E)
        run: docker-compose -f docker-compose.ci.yml exec -T api yarn test:e2e --forceExit

      - name: Stop the Docker stack
        run: docker-compose -f docker-compose.ci.yml down -v
